# Makefile for processing mountain climbing records
.DELETE_ON_ERROR:

all: ;

import:
	./import_mountain_records.sh
	./import_visited_mountains.sh

unify: ;

clean: ;

.PHONY: all import unify clean
